# -*- coding: utf-8 -*-
"""
action_executor.py
Handles post-dialogue actions generated by the AI summarization engine ([DO=...] system).
Currently implements:
- visit_lot: The interlocutor NPC travels to the active Sim's home lot and rings the doorbell / visits.
"""

from typing import Optional, Any
from ai_social_pc.logger import log, log_exception
from ai_social_pc.localization import get_game_language
from ai_social_pc.ui_chat import show_chat_notification

try:
    import services
    import sims4.resources
    import alarms
    from date_and_time import create_time_span
    try:
        from objects import ALL_HIDDEN_REASONS
    except Exception:
        ALL_HIDDEN_REASONS = 0
except ImportError:
    services = None
    sims4 = None
    alarms = None
    create_time_span = None
    ALL_HIDDEN_REASONS = 0


def _is_en() -> bool:
    try:
        return (get_game_language() == "en")
    except Exception:
        return False


def _find_sim_info_by_name(name_str: str) -> Optional[Any]:
    if not name_str or services is None:
        return None
    # Normalize underscores and punctuation to spaces
    clean_target = name_str.replace("_", " ").strip().lower()
    sim_info_mgr = services.sim_info_manager() if hasattr(services, "sim_info_manager") else None
    if sim_info_mgr is None:
        return None

    # Pass 1: exact full name or starts with
    for s_info in sim_info_mgr.get_all():
        f_name = (getattr(s_info, "first_name", "") or "").lower()
        l_name = (getattr(s_info, "last_name", "") or "").lower()
        full_n = f"{f_name} {l_name}".strip()
        if clean_target == full_n or clean_target == f_name:
            return s_info

    # Pass 2: substring match
    for s_info in sim_info_mgr.get_all():
        f_name = (getattr(s_info, "first_name", "") or "").lower()
        l_name = (getattr(s_info, "last_name", "") or "").lower()
        full_n = f"{f_name} {l_name}".strip()
        if clean_target in full_n or (f_name and f_name in clean_target):
            return s_info

    # Pass 3: match words
    words = [w for w in clean_target.split() if len(w) > 2]
    if words:
        for s_info in sim_info_mgr.get_all():
            f_name = (getattr(s_info, "first_name", "") or "").lower()
            l_name = (getattr(s_info, "last_name", "") or "").lower()
            if any(w == f_name or w == l_name for w in words):
                return s_info

    return None


def _resolve_sim_info_by_name(name_str: str, actor_sim_info: Any = None, recipient_sim_info: Any = None) -> Optional[Any]:
    """
    Resolves a Sim name string to a SimInfo object.
    Checks recipient and actor first for fast, accurate matching in dialogues and group chats,
    then falls back to full save search.
    """
    if not name_str or services is None:
        return None
    clean = str(name_str).replace("_", " ").strip().lower()

    # 1. Quick match with recipient
    if recipient_sim_info is not None:
        rf = (getattr(recipient_sim_info, "first_name", "") or "").lower()
        rl = (getattr(recipient_sim_info, "last_name", "") or "").lower()
        rfull = f"{rf} {rl}".strip()
        if clean == rfull or clean == rf or clean in rfull or rfull in clean or (rf and rf in clean):
            return recipient_sim_info

    # 2. Quick match with actor
    if actor_sim_info is not None:
        af = (getattr(actor_sim_info, "first_name", "") or "").lower()
        al = (getattr(actor_sim_info, "last_name", "") or "").lower()
        afull = f"{af} {al}".strip()
        if clean == afull or clean == af or clean in afull or afull in clean or (af and af in clean):
            return actor_sim_info

    # 3. Global search across all Sims in active save
    return _find_sim_info_by_name(name_str)


def execute_post_chat_actions(actions: list, actor_sim_info: Any, recipient_sim_info: Any = None, feedback_fn: Any = None):
    """
    Executes multiple post-chat actions (e.g. several group chat members agreeing to visit or travel).
    Dispatches visiting members together simultaneously, and travel groups together.
    """
    if not actions:
        return

    visit_actors = []
    travel_actors = []
    other_actions = []

    for act in actions:
        if isinstance(act, dict):
            actor_name = act.get("actor")
            act_type = str(act.get("type") or "").strip().lower()
        elif isinstance(act, (list, tuple)) and len(act) >= 2:
            actor_name = act[0]
            act_type = str(act[1] or "").strip().lower()
        else:
            continue
        if not actor_name or not act_type:
            continue

        if act_type == "visit_lot":
            visit_actors.append(actor_name)
        elif act_type in ("travel_together", "travel", "go_out", "hang_out"):
            travel_actors.append(actor_name)
        else:
            other_actions.append((actor_name, act_type))

    # 1. Group visit: summon all agreed friends together at once
    if visit_actors:
        resolved_guests = []
        for a_name in visit_actors:
            s_info = _resolve_sim_info_by_name(a_name, actor_sim_info, recipient_sim_info)
            if s_info is not None and s_info not in resolved_guests:
                resolved_guests.append(s_info)

        if len(resolved_guests) > 1:
            _handle_visit_lot(resolved_guests, actor_sim_info, feedback_fn=feedback_fn)
        elif len(resolved_guests) == 1:
            _handle_visit_lot(resolved_guests[0], actor_sim_info, feedback_fn=feedback_fn)
        else:
            for a_name in visit_actors:
                execute_post_chat_action(a_name, "visit_lot", actor_sim_info, recipient_sim_info, feedback_fn=feedback_fn)

    # 2. Group travel: open Map View with all agreed friends together
    if travel_actors:
        resolved_comps = []
        for a_name in travel_actors:
            s_info = _resolve_sim_info_by_name(a_name, actor_sim_info, recipient_sim_info)
            if s_info is not None and s_info not in resolved_comps:
                resolved_comps.append(s_info)

        # Host must ALWAYS be the player's active selectable Sim
        active_sim_info = services.active_sim_info() if hasattr(services, "active_sim_info") else None
        host = active_sim_info or actor_sim_info
        host_id = getattr(host, "sim_id", 0)

        # Companions are the other Sims, strictly excluding the host
        filtered_comps = [c for c in resolved_comps if getattr(c, "sim_id", 0) != host_id]

        # Fallback to recipient or actor if LLM outputted player's name in WHODO
        if not filtered_comps and recipient_sim_info is not None:
            r_id = getattr(recipient_sim_info, "sim_id", 0)
            if r_id != host_id:
                filtered_comps = [recipient_sim_info]
        if not filtered_comps and actor_sim_info is not None:
            a_id = getattr(actor_sim_info, "sim_id", 0)
            if a_id != host_id:
                filtered_comps = [actor_sim_info]

        if filtered_comps:
            _handle_travel_together(filtered_comps, host, feedback_fn=feedback_fn)
        else:
            for a_name in travel_actors:
                execute_post_chat_action(a_name, "travel_together", host, recipient_sim_info, feedback_fn=feedback_fn)

    # 3. Other individual actions (e.g. wicked_sex)
    for a_name, a_type in other_actions:
        execute_post_chat_action(a_name, a_type, actor_sim_info, recipient_sim_info, feedback_fn=feedback_fn)


def execute_post_chat_action(action_actor_name: str, action_type: str, actor_sim_info: Any, recipient_sim_info: Any, delay_minutes: int = 0, feedback_fn: Any = None):
    """
    Dispatcher for post-chat actions returned by Synapse Bridge.
    Called asynchronously from memory_manager after chat summarization.
    """
    if not action_type:
        return

    clean_action = str(action_type).strip().lower()
    raw_actor = str(action_actor_name or "").strip()
    norm_actor = raw_actor.replace("_", " ").strip()
    log(f"[ACTION EXECUTOR] Processing action: [WHODO={norm_actor}] [DO={clean_action}]")
    if feedback_fn:
        try:
            feedback_fn(f"[ACTION DO] Processing action: [WHODO={norm_actor}] [DO={clean_action}]")
        except Exception:
            pass

    # If action_actor_name contains multiple comma/semicolon-separated names (e.g. from group chat),
    # handle group visits or group travels together
    if norm_actor and ("," in norm_actor or ";" in norm_actor):
        import re
        raw_parts = [p.strip() for p in re.split(r'[,;]+', norm_actor) if p.strip()]
        if len(raw_parts) > 1:
            if clean_action == "visit_lot":
                resolved_guests = [_resolve_sim_info_by_name(p, actor_sim_info, recipient_sim_info) for p in raw_parts]
                resolved_guests = [g for g in resolved_guests if g is not None]
                if len(resolved_guests) > 1:
                    _handle_visit_lot(resolved_guests, actor_sim_info, feedback_fn=feedback_fn)
                    return
            elif clean_action in ("travel_together", "travel", "go_out", "hang_out"):
                active_sim_info = services.active_sim_info() if hasattr(services, "active_sim_info") else None
                host = active_sim_info or actor_sim_info
                host_id = getattr(host, "sim_id", 0)
                resolved_comps = [_resolve_sim_info_by_name(p, actor_sim_info, recipient_sim_info) for p in raw_parts]
                filtered_comps = [c for c in resolved_comps if c is not None and getattr(c, "sim_id", 0) != host_id]
                if not filtered_comps and recipient_sim_info is not None and getattr(recipient_sim_info, "sim_id", 0) != host_id:
                    filtered_comps = [recipient_sim_info]
                if filtered_comps:
                    _handle_travel_together(filtered_comps, host, feedback_fn=feedback_fn)
                    return
            for p in raw_parts:
                execute_post_chat_action(p, action_type, actor_sim_info, recipient_sim_info, feedback_fn=feedback_fn)
            return

    # Resolve actor sim_info
    guest_info = None
    host_info = actor_sim_info

    # Check recipient_sim_info first (most common: active player invites recipient NPC)
    r_name = ""
    if recipient_sim_info is not None:
        r_f = getattr(recipient_sim_info, "first_name", "") or ""
        r_l = getattr(recipient_sim_info, "last_name", "") or ""
        r_name = f"{r_f} {r_l}".strip()

    a_name = ""
    if actor_sim_info is not None:
        a_f = getattr(actor_sim_info, "first_name", "") or ""
        a_l = getattr(actor_sim_info, "last_name", "") or ""
        a_name = f"{a_f} {a_l}".strip()

    if norm_actor:
        actor_clean = norm_actor.lower()
        if r_name and (actor_clean in r_name.lower() or r_name.lower() in actor_clean):
            guest_info = recipient_sim_info
            host_info = actor_sim_info
        elif a_name and (actor_clean in a_name.lower() or a_name.lower() in actor_clean):
            guest_info = actor_sim_info
            host_info = recipient_sim_info
        else:
            guest_info = _find_sim_info_by_name(norm_actor)

    # Fallback to recipient if still undetermined
    if guest_info is None and recipient_sim_info is not None:
        guest_info = recipient_sim_info

    # Dispatch specific action
    if clean_action == "visit_lot":
        if guest_info is None:
            err_msg = f"Could not resolve SimInfo for '{norm_actor}'. Action aborted."
            log(f"[ACTION EXECUTOR] {err_msg}", level="WARN")
            if feedback_fn:
                try:
                    feedback_fn(f"[ACTION DO] {err_msg}")
                except Exception:
                    pass
            return
        _handle_visit_lot(guest_info, host_info, feedback_fn=feedback_fn)
    elif clean_action in ("travel_together", "travel", "go_out", "hang_out"):
        active_sim_info = services.active_sim_info() if hasattr(services, "active_sim_info") else None
        host = active_sim_info or host_info
        host_id = getattr(host, "sim_id", 0)

        companion = guest_info
        if companion is None or getattr(companion, "sim_id", 0) == host_id:
            if recipient_sim_info is not None and getattr(recipient_sim_info, "sim_id", 0) != host_id:
                companion = recipient_sim_info
            elif actor_sim_info is not None and getattr(actor_sim_info, "sim_id", 0) != host_id:
                companion = actor_sim_info

        if companion is not None and getattr(companion, "sim_id", 0) != host_id:
            _handle_travel_together([companion], host, feedback_fn=feedback_fn)
        else:
            log(f"[ACTION EXECUTOR] Could not resolve a valid companion for travel_together with host {host_id}.", level="WARN")
    elif clean_action in ("ask_on_date", "date", "ask_date", "go_on_date", "start_date"):
        active_sim_info = services.active_sim_info() if hasattr(services, "active_sim_info") else None
        host = active_sim_info or host_info
        host_id = getattr(host, "sim_id", 0)

        companion = guest_info
        if companion is None or getattr(companion, "sim_id", 0) == host_id:
            if recipient_sim_info is not None and getattr(recipient_sim_info, "sim_id", 0) != host_id:
                companion = recipient_sim_info
            elif actor_sim_info is not None and getattr(actor_sim_info, "sim_id", 0) != host_id:
                companion = actor_sim_info

        if companion is not None and getattr(companion, "sim_id", 0) != host_id:
            _handle_ask_on_date(companion, host, feedback_fn=feedback_fn)
        else:
            log(f"[ACTION EXECUTOR] Could not resolve a valid companion for ask_on_date with host {host_id}.", level="WARN")
    elif any(clean_action.startswith(m_act) for m_act in ("send_money", "borrow_money", "give_money", "pay_money", "transfer_money", "receive_money", "get_money", "loan")):
        _handle_money_action(norm_actor, clean_action, host_info, recipient_sim_info, feedback_fn=feedback_fn)
    elif clean_action in ("wicked_sex", "sex", "ww_sex", "have_sex", "woohoo"):
        if guest_info is None:
            err_msg = f"Could not resolve SimInfo for '{norm_actor}'. Action aborted."
            log(f"[ACTION EXECUTOR] {err_msg}", level="WARN")
            return
        _handle_wicked_sex(guest_info, host_info, feedback_fn=feedback_fn)
    else:
        log(f"[ACTION EXECUTOR] Action '{clean_action}' is not supported yet.", level="WARN")


def _handle_visit_lot(guest_sim_info: Any, host_sim_info: Any, feedback_fn: Any = None):
    """
    Executes the 'visit_lot' action immediately:
    Handles single SimInfo or a collection of SimInfos (for group chat simultaneous arrivals).
    1. Filters out active Sim and already-present Sims.
    2. Displays notification to the player (single or collective).
    3. Starts the visit situation with all guests simultaneously in one situation guest list.
    """
    if services is None:
        return

    def _msg_out(text: str, level: str = "INFO"):
        log(f"[ACTION EXECUTOR] {text}", level=level)
        if feedback_fn:
            try:
                feedback_fn(f"[ACTION DO] {text}")
            except Exception:
                pass

    if isinstance(guest_sim_info, (list, tuple, set)):
        guests = [g for g in guest_sim_info if g is not None]
    else:
        guests = [guest_sim_info] if guest_sim_info is not None else []

    if not guests:
        _msg_out("No valid guest SimInfos provided for visit_lot.", level="WARN")
        return

    active_sim_info = services.active_sim_info() if hasattr(services, "active_sim_info") else None
    active_id = getattr(active_sim_info, "sim_id", 0)

    # Filter out active sim and duplicates
    unique_guests = []
    seen_ids = set()
    for g in guests:
        gid = getattr(g, "sim_id", 0)
        if gid and gid != active_id and gid not in seen_ids:
            seen_ids.add(gid)
            unique_guests.append(g)

    if not unique_guests:
        _msg_out("All specified guests are either the active sim or duplicates.")
        return

    is_en = _is_en()

    # Separate into already-instanced and uninstanced
    uninstanced_guests = []
    for g in unique_guests:
        g_inst = g.get_sim_instance(allow_hidden_flags=ALL_HIDDEN_REASONS) if hasattr(g, "get_sim_instance") else None
        if g_inst is not None:
            _msg_out(f"Sim {getattr(g, 'first_name', '')} is already present on the active lot! Routing towards front door/host...")
            _ensure_front_door_route(g, host_sim_info, out_fn=_msg_out)
        else:
            uninstanced_guests.append(g)

    if not uninstanced_guests:
        _msg_out("All guests are already present on the active lot.")
        return

    # Notification
    if len(uninstanced_guests) == 1:
        first_n = getattr(uninstanced_guests[0], "first_name", "") or ("Sim" if is_en else "Персонаж")
        title = "Guest on the Way" if is_en else "Гость в пути"
        msg = f"{first_n} agreed to hang out and is heading to your place right now!" if is_en else f"{first_n} согласился прийти в гости и уже направляется к вам домой!"
        lead_sim = uninstanced_guests[0]
    else:
        names_list = [getattr(g, "first_name", "") or ("Sim" if is_en else "Персонаж") for g in uninstanced_guests]
        names_str = ", ".join(names_list)
        title = "Guests on the Way" if is_en else "Гости в пути"
        msg = f"{names_str} agreed to hang out and are heading to your place right now!" if is_en else f"{names_str} согласились прийти в гости и уже направляются к вам домой!"
        lead_sim = uninstanced_guests[0]

    show_chat_notification(title, msg, sim_info=lead_sim)
    _msg_out(f"Notified player of incoming visit from: {', '.join(getattr(g, 'first_name', '') for g in uninstanced_guests)}")

    # Start situation with all uninstanced guests at once!
    _start_visit_situation(uninstanced_guests, host_sim_info, feedback_fn=feedback_fn)


def _ensure_front_door_route(guest_sim_info: Any, host_sim_info: Any, out_fn: Any = None):
    """
    If the guest Sim is instanced and idle (e.g. standing at the portal with no queued interaction),
    pushes an interaction to ring the front doorbell, knock, or route towards the front door / host.
    """
    guest = guest_sim_info.get_sim_instance(allow_hidden_flags=ALL_HIDDEN_REASONS) if hasattr(guest_sim_info, "get_sim_instance") else None
    if guest is None:
        return

    # Check if guest is already actively routing or running an interaction
    has_activity = False
    try:
        if hasattr(guest, "si_state") and guest.si_state is not None and len(guest.si_state) > 0:
            has_activity = True
        elif hasattr(guest, "queue") and guest.queue is not None and len(guest.queue) > 0:
            has_activity = True
    except Exception:
        pass

    if has_activity:
        if out_fn:
            out_fn(f"Sim {guest_sim_info.first_name} already has active interaction/route in progress.")
        return

    # Look for front door
    try:
        door_service = services.get_door_service() if hasattr(services, "get_door_service") else None
        front_door = door_service.get_front_door() if door_service is not None else None
        if front_door is not None:
            door_affordances = front_door.super_affordances() if hasattr(front_door, "super_affordances") else ()
            ring_aff = None
            for aff in door_affordances:
                name = getattr(aff, "__name__", "").lower()
                if "ring" in name or "doorbell" in name or "knock" in name:
                    ring_aff = aff
                    break

            if ring_aff is not None:
                pushed = guest.push_super_affordance(ring_aff, target=front_door)
                if out_fn:
                    out_fn(f"Pushed doorbell affordance '{ring_aff.__name__}' on front door for {guest_sim_info.first_name} (result={pushed})")
                return
    except Exception as e_door:
        log(f"[ACTION EXECUTOR] Front door approach check: {e_door}", level="DEBUG")


def _start_visit_situation(guest_sim_infos: Any, host_sim_info: Any, feedback_fn: Any = None):
    """
    Creates and starts the visit situation in the active zone immediately.
    Accepts a single SimInfo or a list of SimInfos (for simultaneous group arrival).
    Populates all guests into a SINGLE SituationGuestList with MUST_SPAWN and EVENT_VIP priority.
    Ensures all Sims are physically spawned simultaneously and routed towards the front door.
    """
    def _out(msg: str, level: str = "INFO"):
        log(f"[ACTION EXECUTOR] {msg}", level=level)
        if feedback_fn:
            try:
                feedback_fn(f"[ACTION DO] {msg}")
            except Exception:
                pass

    if services is None:
        _out("Services module unavailable.", level="ERROR")
        return False

    if isinstance(guest_sim_infos, (list, tuple, set)):
        guests = [g for g in guest_sim_infos if g is not None]
    else:
        guests = [guest_sim_infos] if guest_sim_infos is not None else []

    if not guests:
        return False

    host_id = getattr(host_sim_info, "sim_id", 0) if host_sim_info is not None else 0
    names_summary = ", ".join(getattr(g, "first_name", "") for g in guests)
    _out(f"Executing simultaneous arrival sequence for [{names_summary}] (Host ID: {host_id})...")

    sit_mgr = services.get_zone_situation_manager() if hasattr(services, "get_zone_situation_manager") else None
    if sit_mgr is None and hasattr(services, "current_zone"):
        zone = services.current_zone()
        sit_mgr = getattr(zone, "situation_manager", None)

    if sit_mgr is None:
        _out("Situation manager unavailable in active zone.", level="ERROR")
        return False

    situation_id = None

    # Step 1: Collect and rank candidate situation types
    try:
        inst_mgr = services.get_instance_manager(sims4.resources.Types.SITUATION) if (sims4 is not None and hasattr(services, "get_instance_manager")) else None
        candidates = []

        if inst_mgr is not None:
            try:
                from situations.visiting.invite_over_situation import InviteOverSituation
            except Exception:
                InviteOverSituation = None

            try:
                from situations.ambient.walkby_ring_doorbell_situation import WalkbyRingDoorBellSituation
            except Exception:
                WalkbyRingDoorBellSituation = None

            try:
                from situations.visiting.visiting_situation_common import VisitingNPCSituation
            except Exception:
                VisitingNPCSituation = None

            inv_subclasses = []
            walkby_subclasses = []
            name_matches = []
            other_visiting = []

            # Blacklist of test, experimental, or unwanted situations
            blacklist = (
                "experiment", "test", "debug", "holiday", "break_in", "breaking",
                "island_spirits", "voodoo", "service", "fire", "grim", "leave",
                "repo", "maid", "paparazzi", "nanny", "repair", "gardener", "delivery"
            )

            for sit_cls in list(inst_mgr.types.values()):
                c_name = getattr(sit_cls, "__name__", "")
                c_lower = c_name.lower()
                c_mod = getattr(sit_cls, "__module__", "").lower()

                if any(bad in c_lower or bad in c_mod for bad in blacklist):
                    continue

                if InviteOverSituation is not None and issubclass(sit_cls, InviteOverSituation):
                    inv_subclasses.append((sit_cls, f"subclass_InviteOver_{c_name}"))
                elif WalkbyRingDoorBellSituation is not None and issubclass(sit_cls, WalkbyRingDoorBellSituation):
                    walkby_subclasses.append((sit_cls, f"subclass_WalkbyRingDoorBell_{c_name}"))
                elif "inviteover" in c_lower or "invite_over" in c_lower:
                    name_matches.append((sit_cls, f"name_inviteover_{c_name}"))
                elif "ringdoorbell" in c_lower or "ring_doorbell" in c_lower:
                    name_matches.append((sit_cls, f"name_ringdoorbell_{c_name}"))
                elif VisitingNPCSituation is not None and issubclass(sit_cls, VisitingNPCSituation):
                    if "npc_visiting_npc" not in c_lower:
                        other_visiting.append((sit_cls, f"subclass_VisitingNPC_{c_name}"))
                elif "visitingnpc" in c_lower or "visiting_npc" in c_lower:
                    if "npc_visiting_npc" not in c_lower:
                        other_visiting.append((sit_cls, f"name_visiting_{c_name}"))

            candidates = inv_subclasses + walkby_subclasses + name_matches + other_visiting

        _out(f"Discovered {len(candidates)} valid candidate situation type(s).")

        from situations.situation_guest_list import SituationGuestList, SituationGuestInfo, SituationInvitationPurpose
        try:
            from situations.bouncer.bouncer_types import RequestSpawningOption, BouncerRequestPriority
        except Exception:
            RequestSpawningOption = None
            BouncerRequestPriority = None

        for sit_cls, tag_desc in candidates:
            try:
                guest_list = SituationGuestList(invite_only=True, host_sim_id=host_id)

                # Safely extract default job
                job = getattr(sit_cls, "default_job", None)
                if callable(job):
                    try:
                        job = job()
                    except Exception:
                        pass
                if job is None and hasattr(sit_cls, "get_default_job"):
                    try:
                        job = sit_cls.get_default_job()
                    except Exception:
                        pass
                if job is None and hasattr(sit_cls, "invited_job"):
                    job = getattr(sit_cls.invited_job, "situation_job", None)
                if job is None and hasattr(sit_cls, "walker_job"):
                    job = getattr(sit_cls.walker_job, "situation_job", None)
                if job is None:
                    job = getattr(sit_cls, "_default_job", None)

                # Search through job containers if still None
                if job is None:
                    for j_attr in ("_jobs", "situation_jobs", "jobs"):
                        j_coll = getattr(sit_cls, j_attr, None)
                        if j_coll:
                            if isinstance(j_coll, (list, tuple, set)) and len(j_coll) > 0:
                                job = next(iter(j_coll))
                                break
                            elif isinstance(j_coll, dict) and len(j_coll) > 0:
                                job = next(iter(j_coll.values()))
                                break

                # Add ALL guests into the single SituationGuestList!
                for g in guests:
                    g_id = getattr(g, "sim_id", 0)
                    if job is not None:
                        guest_info = SituationGuestInfo.construct_from_purpose(
                            g_id,
                            job,
                            SituationInvitationPurpose.INVITED,
                        )
                    else:
                        guest_info = SituationGuestInfo(
                            g_id,
                            None,
                            SituationInvitationPurpose.INVITED,
                        )

                    if RequestSpawningOption is not None:
                        guest_info.spawning_option = RequestSpawningOption.MUST_SPAWN
                    if BouncerRequestPriority is not None:
                        guest_info.request_priority = BouncerRequestPriority.EVENT_VIP
                    guest_info.expectation_preference = True

                    guest_list.add_guest_info(guest_info)

                situation_id = sit_mgr.create_situation(sit_cls, guest_list=guest_list, user_facing=False)
                if situation_id is not None:
                    _out(f"Successfully started group situation '{sit_cls.__name__}' ({tag_desc}) for {len(guests)} Sims with ID: {situation_id}!")
                    break
            except Exception as e_sit:
                _out(f"Candidate '{getattr(sit_cls, '__name__', '')}' failed: {e_sit}", level="WARN")

    except Exception as e:
        log_exception("Failed searching/starting tuned situation", e)

    # Step 2: Fallback to native active_venue.summon_npcs if no situation started
    if situation_id is None:
        try:
            current_zone = services.current_zone() if hasattr(services, "current_zone") else None
            venue_service = getattr(current_zone, "venue_service", None) if current_zone else None
            active_venue = getattr(venue_service, "active_venue", None) if venue_service else None
            if active_venue is not None and hasattr(active_venue, "summon_npcs"):
                from venues.venue_constants import NPCSummoningPurpose
                active_venue.summon_npcs(tuple(guests), NPCSummoningPurpose.DEFAULT, host_sim_info=host_sim_info)
                _out(f"Invoked native active_venue.summon_npcs for {len(guests)} Sims simultaneously!")
        except Exception as e_sum:
            log_exception("Failed active_venue.summon_npcs fallback", e_sum)

    # Step 3: For each guest, ensure instanced on lot, approach door, and make available
    for g in guests:
        g_name = getattr(g, "first_name", "") or "Sim"
        try:
            sim_inst = g.get_sim_instance(allow_hidden_flags=ALL_HIDDEN_REASONS) if hasattr(g, "get_sim_instance") else None
            if sim_inst is None:
                _out(f"Sim {g_name} is not yet instanced on lot. Invoking SimSpawner.spawn_sim...")
                from sims.sim_spawner import SimSpawner
                spawn_res = SimSpawner.spawn_sim(g)
                sim_inst = g.get_sim_instance(allow_hidden_flags=ALL_HIDDEN_REASONS) if hasattr(g, "get_sim_instance") else None
                if sim_inst is not None:
                    _out(f"SimSpawner successfully spawned {g_name} onto the active lot!")
                else:
                    _out(f"SimSpawner called for {g_name} (spawn_res={spawn_res}), instance registration in progress.", level="INFO")
            else:
                _out(f"Verified Sim {g_name} is active and instanced on the current lot!")
        except Exception as e_spawn:
            log_exception(f"Failed SimSpawner spawn_sim fallback for {g_name}", e_spawn)

        # Ensure front door routing / doorbell approach
        _ensure_front_door_route(g, host_sim_info, out_fn=_out)

        # Make Sim available
        try:
            sit_mgr.make_waiting_player_sim_available(g)
        except Exception:
            pass

    _out(f"SUCCESS: Arrival sequence complete for [{names_summary}] (situation_id={situation_id})!")
    return (situation_id is not None)


def _handle_travel_together(companion_sim_infos: Any, host_sim_info: Any, feedback_fn: Any = None):
    """
    Executes the 'travel_together' action:
    Immediately opens The Sims 4 World Map View with the player's active Sim as Host and all agreed companions
    in the traveling party, allowing the player to choose any valid lot (bar, club, cafe, park, etc.).
    """
    if services is None:
        return

    def _msg_out(text: str, level: str = "INFO"):
        log(f"[ACTION EXECUTOR] {text}", level=level)
        if feedback_fn:
            try:
                feedback_fn(f"[ACTION DO] {text}")
            except Exception:
                pass

    if isinstance(companion_sim_infos, (list, tuple, set)):
        companions = [c for c in companion_sim_infos if c is not None]
    else:
        companions = [companion_sim_infos] if companion_sim_infos is not None else []

    # Host MUST ALWAYS be the player's active selectable Sim so active household control is preserved!
    active_sim_info = services.active_sim_info() if hasattr(services, "active_sim_info") else None
    if active_sim_info is not None:
        host_sim_info = active_sim_info
    elif host_sim_info is None:
        host_sim_info = active_sim_info

    host_id = getattr(host_sim_info, "sim_id", 0) if host_sim_info is not None else 0
    if not host_id:
        _msg_out("Error: Host Sim ID is invalid or active Sim not found.", level="ERROR")
        return

    # Filter companions to eliminate host and duplicates
    unique_companions = []
    seen_ids = {host_id}
    for c in companions:
        cid = getattr(c, "sim_id", 0)
        if cid and cid not in seen_ids:
            seen_ids.add(cid)
            unique_companions.append(c)

    # If unique_companions is empty, travel_together cannot proceed (cannot travel alone under travel_together)
    if not unique_companions:
        _msg_out("No valid companions found for travel_together. Action aborted.", level="WARN")
        return

    is_en = _is_en()
    host_name = getattr(host_sim_info, "first_name", "") or ("You" if is_en else "Вы")

    comp_names = [getattr(c, "first_name", "") or ("Sim" if is_en else "Персонаж") for c in unique_companions]
    comp_names_str = ", ".join(comp_names)
    title = "Heading Out Together" if is_en else "Совместная прогулка"
    msg = (
        f"{comp_names_str} agreed to go out! Your Sim is pulling out their phone to travel together."
        if is_en else
        f"{comp_names_str} согласились пойти погулять вместе! Персонаж достаёт телефон, чтобы отправиться в путь."
    )
    lead_sim = unique_companions[0]

    # Show notification to the player
    show_chat_notification(title, msg, sim_info=lead_sim)
    _msg_out(f"Triggering native phone travel: Host '{host_name}' with companions: [{comp_names_str}]")

    # Push native phone travel affordance with companion pre-selected
    _push_native_phone_travel(host_sim_info, unique_companions, feedback_fn=_msg_out)


def _push_native_phone_travel(host_sim_info: Any, unique_companions: list, feedback_fn: Any = None) -> bool:
    """
    Plan V: Natively pushes the EA Phone Travel interaction to the player's active Sim,
    automatically forming an in-game ensemble/group with companions so they are pre-selected.
    The game uses 100% official vanilla EA code to open the travel picker and transition zones cleanly.
    """
    is_en = _is_en()
    try:
        from objects import ALL_HIDDEN_REASONS
        from interactions.context import InteractionContext, QueueInsertStrategy
        from interactions.priority import Priority
        from interactions.aop import AffordanceObjectPair

        host_sim = host_sim_info.get_sim_instance(allow_hidden_flags=ALL_HIDDEN_REASONS) if hasattr(host_sim_info, "get_sim_instance") else None
        if host_sim is None:
            log("[PHONE TRAVEL] Host Sim instance is None (not on lot).", level="WARN")
            if feedback_fn:
                feedback_fn("Error: Active Sim instance not found." if is_en else "Ошибка: Активный персонаж не найден в мире.")
            return False

        # 1. Gather companion Sim instances and form an in-game Ensemble / Group
        comp_instances = []
        for c in unique_companions:
            c_inst = c.get_sim_instance(allow_hidden_flags=ALL_HIDDEN_REASONS) if hasattr(c, "get_sim_instance") else None
            if c_inst is not None and c_inst != host_sim:
                comp_instances.append(c_inst)

        if comp_instances:
            try:
                ensemble_service = services.ensemble_service() if hasattr(services, "ensemble_service") else None
                if ensemble_service is not None:
                    ens_type = getattr(ensemble_service, "DEFAULT_ENSEMBLE_TYPE", None)
                    if ens_type is not None:
                        ensemble_service.create_ensemble(ens_type, [host_sim] + comp_instances)
                        log(f"[PHONE TRAVEL] Formed in-game ensemble with Host {host_sim.id} and {len(comp_instances)} companion(s).")
            except Exception as e_ens:
                log_exception("Error creating travel ensemble", e_ens)

        # 2. Find the genuine Phone Travel affordance on the active Sim
        # (Must be genuine EA travel to venue/lot, NOT date, NOT hangout, NOT moving out, NOT vacation!)
        travel_aff = None
        candidates = []
        BAD_KEYWORDS = (
            "move", "split", "household", "vacation", "rent", "stayover",
            "date", "hangout", "cad", "volunteer", "service", "getaway", "club"
        )
        if hasattr(host_sim, "_phone_affordances") and host_sim._phone_affordances:
            for aff in host_sim._phone_affordances:
                a_name = getattr(aff, "__name__", "")
                a_name_lower = a_name.lower()
                cat = getattr(aff, "category", None)
                cat_name = getattr(cat, "__name__", str(cat)).lower() if cat is not None else ""

                # Ignore non-travel actions like dates, hangouts, moving out, volunteer, getaways, etc.
                if any(bad in a_name_lower for bad in BAD_KEYWORDS):
                    continue

                if "travel" in cat_name or "travel" in a_name_lower or "inviteto" in a_name_lower:
                    candidates.append((aff, a_name, cat_name))

        if candidates:
            log(f"[PHONE TRAVEL] Valid travel candidates on Sim: {[(c[1], c[2]) for c in candidates]}")
            # Priority 1: Genuine EA phone travel picker (phone_Picker_InviteTo_NEW)
            for c in candidates:
                if "inviteto" in c[1].lower():
                    travel_aff = c[0]
                    break
            # Priority 2: Has both 'travel' and ('with' or 'picker') in affordance name
            if travel_aff is None:
                for c in candidates:
                    nl = c[1].lower()
                    if "travel" in nl and ("with" in nl or "picker" in nl):
                        travel_aff = c[0]
                        break
            # Priority 3: Candidates strictly in phonecategory_travel
            if travel_aff is None:
                for c in candidates:
                    if "travel" in c[2]:
                        travel_aff = c[0]
                        break
            # Priority 4: First remaining valid candidate
            if travel_aff is None:
                travel_aff = candidates[0][0]

            log(f"[PHONE TRAVEL] Selected phone travel affordance: {travel_aff.__name__}")

        if travel_aff is None:
            try:
                aff_mgr = services.affordance_manager() if hasattr(services, "affordance_manager") else None
                if aff_mgr is not None:
                    for aff in aff_mgr.types.values():
                        a_name = getattr(aff, "__name__", "").lower()
                        if ("phone_picker_inviteto" in a_name or ("phone" in a_name and "travel" in a_name)) and not any(bad in a_name for bad in BAD_KEYWORDS):
                            travel_aff = aff
                            log(f"[PHONE TRAVEL] Found phone travel affordance from aff_mgr: {aff.__name__}")
                            break
            except Exception:
                pass

        if travel_aff is None:
            try:
                from objects.terrain import TravelSuperInteraction
                travel_aff = TravelSuperInteraction
                log("[PHONE TRAVEL] Falling back to objects.terrain.TravelSuperInteraction")
            except Exception:
                pass

        if travel_aff is None:
            log("[PHONE TRAVEL] Could not find any valid travel affordance.", level="ERROR")
            if feedback_fn:
                feedback_fn("Error: Travel affordance not found." if is_en else "Ошибка: Действие путешествия не найдено.")
            return False

        # 3. Determine target: phone interactions typically target the active sim (host)
        client = services.client_manager().get_first_client() if hasattr(services, "client_manager") else None
        context = InteractionContext(
            host_sim,
            InteractionContext.SOURCE_PIE_MENU,
            Priority.High,
            client=client,
            insert_strategy=QueueInsertStrategy.FIRST
        )

        target_obj = host_sim
        aop = AffordanceObjectPair(travel_aff, target_obj, travel_aff, None)
        res = aop.test_and_execute(context)
        if not res and comp_instances:
            # Fallback: try targeting lead companion if interaction requires target Sim
            target_obj = comp_instances[0]
            aop = AffordanceObjectPair(travel_aff, target_obj, travel_aff, None)
            res = aop.test_and_execute(context)
        if not res:
            res = aop.execute(context)

        log(f"[PHONE TRAVEL] Successfully pushed {getattr(travel_aff, '__name__', str(travel_aff))} to Sim {host_sim.id} with target {target_obj.id}: result={res}")
        if feedback_fn:
            feedback_fn("Native phone travel started! Pick your destination in the game menu." if is_en else "Телефонное действие запущено! Выберите место назначения в игровом меню.")
        return bool(res)
    except Exception as e:
        log_exception("Failed to push native phone travel interaction", e)
        if feedback_fn:
            feedback_fn(f"Error starting phone travel: {e}" if is_en else f"Ошибка запуска телефонного путешествия: {e}")
        return False


def hook_travel_commands():
    """No-op: Plan V uses 100% native EA phone interactions, keeping engine command handlers clean."""
    pass


# =====================================================================
# Romantic Date Action Handlers ([DO=ask_on_date])
# Standard Base Game Date (strictly excluding Lovestruck CAD)
# =====================================================================

def _handle_ask_on_date(companion_sim_info: Any, host_sim_info: Any, feedback_fn: Any = None):
    """
    Triggers the classic Base Game Date event via phone interaction.
    Excludes Lovestruck CAD to ensure standard EA Base Game date behavior.
    """
    is_en = _is_en()
    try:
        host_sim = host_sim_info.get_sim_instance(allow_hidden_flags=ALL_HIDDEN_REASONS) if hasattr(host_sim_info, "get_sim_instance") else None
        if host_sim is None:
            active_info = services.active_sim_info() if hasattr(services, "active_sim_info") else None
            host_sim = active_info.get_sim_instance(allow_hidden_flags=ALL_HIDDEN_REASONS) if active_info else None

        if host_sim is None:
            log("[PHONE DATE] Active host Sim instance not found.", level="WARN")
            if feedback_fn:
                feedback_fn("Error: Active host Sim not found." if is_en else "Ошибка: Активный сим не найден.")
            return

        comp_sim = companion_sim_info.get_sim_instance(allow_hidden_flags=ALL_HIDDEN_REASONS) if hasattr(companion_sim_info, "get_sim_instance") else None
        comp_name = f"{getattr(companion_sim_info, 'first_name', '')} {getattr(companion_sim_info, 'last_name', '')}".strip()

        title = "Romantic Date" if is_en else "Романтическое свидание"
        notif_msg = (
            f"You and {comp_name} are going on a date! Choose your venue on the map."
            if is_en else
            f"Вы с {comp_name} отправляетесь на свидание! Выберите заведение на карте."
        )
        show_chat_notification(title, notif_msg)

        _push_native_phone_date(host_sim, comp_sim, companion_sim_info, is_en=is_en, feedback_fn=feedback_fn)
    except Exception as e:
        log_exception("Error in _handle_ask_on_date", e)


def _push_native_phone_date(host_sim: Any, comp_sim: Any, comp_info: Any, is_en: bool = False, feedback_fn: Any = None) -> bool:
    try:
        from interactions.context import InteractionContext, QueueInsertStrategy
        from interactions.priority import Priority
        from interactions.aop import AffordanceObjectPair

        # Form ensemble with companion
        if comp_sim is not None:
            try:
                ensemble_service = services.ensemble_service() if hasattr(services, "ensemble_service") else None
                if ensemble_service is not None:
                    ens_type = getattr(ensemble_service, "DEFAULT_ENSEMBLE_TYPE", None)
                    if ens_type is not None:
                        ensemble_service.create_ensemble(ens_type, [host_sim, comp_sim])
                        log(f"[PHONE DATE] Formed in-game ensemble with Host {host_sim.id} and {comp_sim.id}.")
            except Exception as e_ens:
                log_exception("Error creating date ensemble", e_ens)

        date_aff = None
        candidates = []
        is_teen = getattr(host_sim, "is_teen", False) or getattr(getattr(host_sim, "sim_info", None), "is_teen", False)

        if hasattr(host_sim, "_phone_affordances") and host_sim._phone_affordances:
            for aff in host_sim._phone_affordances:
                a_name = getattr(aff, "__name__", "")
                a_name_lower = a_name.lower()
                # Strictly ignore CAD (Lovestruck expansion Create-A-Date)
                if "cad" in a_name_lower:
                    continue
                if "date" in a_name_lower:
                    candidates.append((aff, a_name_lower))

        if candidates:
            # Prefer teen if host is teen, else prefer adult Base Game date
            target_key = "teen" if is_teen else "adult"
            for c in candidates:
                if target_key in c[1]:
                    date_aff = c[0]
                    break
            if date_aff is None:
                date_aff = candidates[0][0]
            log(f"[PHONE DATE] Selected base game date affordance: {date_aff.__name__}")

        if date_aff is None:
            try:
                aff_mgr = services.affordance_manager() if hasattr(services, "affordance_manager") else None
                if aff_mgr is not None:
                    target_key = "teen" if is_teen else "adult"
                    for aff in aff_mgr.types.values():
                        an = getattr(aff, "__name__", "").lower()
                        if "phone" in an and "date" in an and "cad" not in an and target_key in an:
                            date_aff = aff
                            log(f"[PHONE DATE] Found base game date affordance from aff_mgr: {aff.__name__}")
                            break
            except Exception:
                pass

        if date_aff is None:
            log("[PHONE DATE] Could not find base game date affordance.", level="ERROR")
            if feedback_fn:
                feedback_fn("Error: Base game date affordance not found." if is_en else "Ошибка: Действие свидания не найдено.")
            return False

        client = services.client_manager().get_first_client() if hasattr(services, "client_manager") else None
        context = InteractionContext(
            host_sim,
            InteractionContext.SOURCE_PIE_MENU,
            Priority.High,
            client=client,
            insert_strategy=QueueInsertStrategy.FIRST
        )

        target_obj = comp_sim if comp_sim is not None else host_sim
        aop = AffordanceObjectPair(date_aff, target_obj, date_aff, None)
        res = aop.test_and_execute(context)
        if not res and target_obj is not host_sim:
            aop = AffordanceObjectPair(date_aff, host_sim, date_aff, None)
            res = aop.test_and_execute(context)
        if not res:
            res = aop.execute(context)

        log(f"[PHONE DATE] Pushed {date_aff.__name__} result={res}")
        if feedback_fn:
            feedback_fn("Base game date started! Choose lot on map." if is_en else "Свидание запущено! Выберите место на карте.")
        return bool(res)
    except Exception as e:
        log_exception("Failed to push base game date interaction", e)
        if feedback_fn:
            feedback_fn(f"Error starting date: {e}" if is_en else f"Ошибка запуска свидания: {e}")
        return False


# =====================================================================
# Simoleon Transfer & Loan Action Handlers ([DO=send_money], [DO=borrow_money])
# =====================================================================

def _handle_money_action(actor_name: str, action_clean: str, host_sim_info: Any, recipient_sim_info: Any, feedback_fn: Any = None):
    """
    Handles transferring simoleons between player household and interlocutor Sim.
    Supports send_money, borrow_money, receive_money, give_money, loan with optional amount (e.g. [DO=send_money:500]).
    """
    import re
    is_en = _is_en()
    try:
        active_sim_info = services.active_sim_info() if hasattr(services, "active_sim_info") else None
        host_info = active_sim_info or host_sim_info
        if host_info is None:
            return

        household = host_info.household if hasattr(host_info, "household") else None
        if household is None or not hasattr(household, "funds"):
            return

        funds = household.funds
        cur_money = getattr(funds, "money", 0)

        # Parse amount from action string (e.g. "send_money:500" or "borrow_money_1000")
        amount = 500
        amt_match = re.search(r'[:_](\d+)', action_clean)
        if amt_match:
            try:
                parsed_amt = int(amt_match.group(1))
                if parsed_amt > 0:
                    amount = parsed_amt
            except Exception:
                amount = 500

        # Determine other participant Sim
        other_info = None
        if recipient_sim_info is not None and getattr(recipient_sim_info, "sim_id", 0) != getattr(host_info, "sim_id", 0):
            other_info = recipient_sim_info
        elif actor_name:
            other_info = _resolve_sim_info_by_name(actor_name, host_info, recipient_sim_info)

        other_name = "Собеседник" if not is_en else "Friend"
        if other_info is not None:
            fn = getattr(other_info, "first_name", "") or ""
            ln = getattr(other_info, "last_name", "") or ""
            other_name = f"{fn} {ln}".strip() or other_name

        # Determine direction:
        # If action is 'borrow_money' or 'take_loan' -> player receives money (+amount) if player borrowed,
        # OR if WHODO is other sim asking player for loan -> player lends money (-amount).
        is_player_paying = False
        act_base = action_clean.split(":")[0].strip()

        is_actor_host = False
        if actor_name and host_info:
            hf = (getattr(host_info, "first_name", "") or "").lower()
            hl = (getattr(host_info, "last_name", "") or "").lower()
            hfull = f"{hf} {hl}".strip()
            an_lower = actor_name.lower()
            if an_lower in hfull or an_lower == hf:
                is_actor_host = True

        if act_base in ("borrow_money", "ask_loan", "take_loan"):
            is_player_paying = not is_actor_host
        elif act_base in ("send_money", "give_money", "pay_money", "transfer_money"):
            is_player_paying = is_actor_host
        elif act_base in ("receive_money", "get_money"):
            is_player_paying = False
        else:
            is_player_paying = is_actor_host

        host_sim = host_info.get_sim_instance(allow_hidden_flags=ALL_HIDDEN_REASONS) if hasattr(host_info, "get_sim_instance") else None

        reason = 0
        try:
            from protocolbuffers import Consts_pb2
            reason = getattr(Consts_pb2, "TELEMETRY_MONEY_CHEAT", 0)
        except Exception:
            pass

        if is_player_paying:
            # Deduct money from household
            if cur_money < amount:
                title = "Недостаточно средств" if not is_en else "Insufficient Funds"
                msg = (
                    f"На счету семьи недостаточно симолеонов для перевода ({amount} §). Текущий баланс: {cur_money} §."
                    if not is_en else
                    f"Not enough simoleons in household funds ({amount} §). Current balance: {cur_money} §."
                )
                show_chat_notification(title, msg, is_error=True)
                if feedback_fn:
                    feedback_fn(msg)
                return

            if hasattr(funds, "remove"):
                try:
                    funds.remove(amount, reason, host_sim)
                except TypeError:
                    funds.remove(amount, reason)
            elif hasattr(funds, "modify_funds"):
                funds.modify_funds(-amount)

            new_bal = getattr(funds, "money", cur_money - amount)
            title = "💸 Денежный перевод" if not is_en else "💸 Money Transfer"
            msg = (
                f"Вы перевели {other_name} {amount:,} §.\nНовый баланс семьи: {new_bal:,} §."
                if not is_en else
                f"You transferred {amount:,} § to {other_name}.\nNew household balance: {new_bal:,} §."
            )
            show_chat_notification(title, msg)
            log(f"[MONEY ACTION] Transferred {amount} to {other_name}. New balance: {new_bal}")
            if feedback_fn:
                feedback_fn(msg)
        else:
            # Add money to household
            if hasattr(funds, "add"):
                try:
                    funds.add(amount, reason, host_sim)
                except TypeError:
                    funds.add(amount, reason)
            elif hasattr(funds, "modify_funds"):
                funds.modify_funds(amount)

            new_bal = getattr(funds, "money", cur_money + amount)
            title = "💸 Денежный перевод" if not is_en else "💸 Money Transfer"
            msg = (
                f"{other_name} перевел(а) вам {amount:,} §!\nНовый баланс семьи: {new_bal:,} §."
                if not is_en else
                f"{other_name} sent you {amount:,} §!\nNew household balance: {new_bal:,} §."
            )
            show_chat_notification(title, msg)
            log(f"[MONEY ACTION] Received {amount} from {other_name}. New balance: {new_bal}")
            if feedback_fn:
                feedback_fn(msg)

    except Exception as e:
        log_exception("Error in _handle_money_action", e)
        if feedback_fn:
            feedback_fn(f"Error processing money action: {e}")



# =====================================================================
# WickedWhims Intimacy & Sex Action Handlers ([DO=wicked_sex])
# =====================================================================

_INTIMACY_WATCHERS = {}


def _is_ww_available() -> bool:
    """Checks if WickedWhims and TurboLib are available in the game environment."""
    try:
        import wickedwhims
        import turbolib2
        return True
    except ImportError:
        return False


def _find_best_bed_object(actor_sim_info: Any = None):
    """
    Finds the best bed on the active lot for intimacy.
    Prioritizes double beds, then sorts by distance to the actor Sim.
    Returns TurboGameObject of the bed, or None if no bed is found.
    """
    if services is None:
        return None
    try:
        try:
            from turbolib2.wrappers.game_object.game_object import TurboGameObject
        except Exception:
            from turbolib2.wrappers.game_object import TurboGameObject
        from wickedwhims.sex.animations.animations_sex_locations import get_sex_location_identifier, SexLocationType
    except Exception:
        return None

    obj_mgr = services.object_manager()
    if obj_mgr is None:
        return None

    actor_sim = None
    if actor_sim_info is not None and hasattr(actor_sim_info, "get_sim_instance"):
        actor_sim = actor_sim_info.get_sim_instance()

    beds = []
    for obj in obj_mgr.get_all():
        try:
            turbo_obj = TurboGameObject(obj)
            loc_id_data = get_sex_location_identifier(turbo_obj)
            loc_type = loc_id_data[0] if isinstance(loc_id_data, (tuple, list)) else loc_id_data
            type_name = str(getattr(loc_type, "name", loc_type)).upper()

            is_bed = False
            is_double = False

            if hasattr(SexLocationType, "DOUBLE_BED") and loc_type == SexLocationType.DOUBLE_BED:
                is_bed = True
                is_double = True
            elif hasattr(SexLocationType, "MURPHY_DOUBLE_BED") and loc_type == SexLocationType.MURPHY_DOUBLE_BED:
                is_bed = True
                is_double = True
            elif hasattr(SexLocationType, "SINGLE_BED") and loc_type == SexLocationType.SINGLE_BED:
                is_bed = True
            elif hasattr(SexLocationType, "BUNK_BED") and loc_type == SexLocationType.BUNK_BED:
                is_bed = True
            elif hasattr(SexLocationType, "BED_ROLL") and loc_type == SexLocationType.BED_ROLL:
                is_bed = True
            elif "BED" in type_name:
                is_bed = True
                is_double = ("DOUBLE" in type_name)

            if is_bed:
                dist = 9999.0
                if actor_sim is not None and hasattr(actor_sim, "position") and hasattr(obj, "position"):
                    dist = (obj.position - actor_sim.position).magnitude()
                beds.append((is_double, dist, turbo_obj))
        except Exception:
            continue

    if beds:
        # Sort double beds first (not is_double -> False comes first), then by distance ascending
        beds.sort(key=lambda item: (not item[0], item[1]))
        return beds[0][2]

    return None


def _handle_wicked_sex(guest_sim_info: Any, host_sim_info: Any, feedback_fn: Any = None):
    """
    Executes the 'wicked_sex' intimacy action between host and guest:
    1. Validates WickedWhims is installed.
    2. If guest is not on the active lot (e.g. texting from elsewhere):
       - Displays notification to the player.
       - Starts arrival sequence (InviteOver situation / SimSpawner).
       - Registers an in-game alarm watching for guest arrival.
       - Once instanced on lot, triggers intimacy.
    3. If guest is already present on lot:
       - Triggers intimacy immediately.
    """
    def _msg_out(text: str, level: str = "INFO"):
        log(f"[ACTION EXECUTOR] {text}", level=level)
        if feedback_fn:
            try:
                feedback_fn(f"[ACTION DO] {text}")
            except Exception:
                pass

    if not _is_ww_available():
        err_msg = "WickedWhims is not installed; cannot execute intimacy action." if _is_en() else "Мод WickedWhims не установлен; невозможно выполнить интимное действие."
        _msg_out(err_msg, level="WARN")
        show_chat_notification("WickedWhims", err_msg, is_error=True)
        return

    guest_id = getattr(guest_sim_info, "sim_id", 0)
    active_sim_info = services.active_sim_info() if (services is not None and hasattr(services, "active_sim_info")) else None
    active_id = getattr(active_sim_info, "sim_id", 0)

    # Cannot have intimacy with self
    if guest_id == active_id and host_sim_info is not None and getattr(host_sim_info, "sim_id", 0) == active_id:
        _msg_out("Guest is the active sim; cannot trigger intimacy with self.", level="WARN")
        return

    # Check if guest is currently on the active lot
    guest_inst = guest_sim_info.get_sim_instance(allow_hidden_flags=ALL_HIDDEN_REASONS) if hasattr(guest_sim_info, "get_sim_instance") else None
    if guest_inst is None:
        first_n = getattr(guest_sim_info, "first_name", "") or ("Sim" if _is_en() else "Персонаж")
        is_en = _is_en()
        title = "Intimate Encounter" if is_en else "Интимная встреча"
        msg = f"{first_n} agreed to be intimate and is heading over right now!" if is_en else f"{first_n} соглашается на интимную близость и уже направляется к вам!"

        show_chat_notification(title, msg, sim_info=guest_sim_info)
        _msg_out(f"Guest {first_n} is off-lot; initiated arrival sequence for intimacy.")

        _start_visit_situation(guest_sim_info, host_sim_info, feedback_fn=feedback_fn)
        _register_intimacy_arrival_watcher(guest_sim_info, host_sim_info, feedback_fn=feedback_fn)
        return

    # Guest is already on the lot -> execute immediately
    _msg_out(f"Sim {guest_sim_info.first_name} is already present on lot! Starting intimacy...")
    _execute_wicked_sex_now(guest_sim_info, host_sim_info, feedback_fn=feedback_fn)


def _register_intimacy_arrival_watcher(guest_sim_info: Any, host_sim_info: Any, feedback_fn: Any = None):
    """
    Registers an in-game alarm watching for the guest Sim to be physically instanced on the active lot.
    Once arrived, triggers the intimacy action.
    """
    if alarms is None or create_time_span is None or services is None:
        return

    guest_id = getattr(guest_sim_info, "sim_id", 0)
    if guest_id in _INTIMACY_WATCHERS:
        try:
            alarms.cancel_alarm(_INTIMACY_WATCHERS[guest_id])
        except Exception:
            pass
        _INTIMACY_WATCHERS.pop(guest_id, None)

    zone_inst = services.current_zone()
    if zone_inst is None:
        return

    ticks_count = [0]

    def _check_arrival(alarm_handle):
        ticks_count[0] += 1
        inst = guest_sim_info.get_sim_instance(allow_hidden_flags=ALL_HIDDEN_REASONS) if hasattr(guest_sim_info, "get_sim_instance") else None
        if inst is not None:
            try:
                alarms.cancel_alarm(alarm_handle)
            except Exception:
                pass
            _INTIMACY_WATCHERS.pop(guest_id, None)
            log(f"[ACTION EXECUTOR] Guest {guest_sim_info.first_name} arrived on lot for intimacy! Triggering WW sex now.")
            _execute_wicked_sex_now(guest_sim_info, host_sim_info, feedback_fn=feedback_fn)
            return

        # Timeout after 45 in-game minutes
        if ticks_count[0] >= 45:
            try:
                alarms.cancel_alarm(alarm_handle)
            except Exception:
                pass
            _INTIMACY_WATCHERS.pop(guest_id, None)
            log(f"[ACTION EXECUTOR] Intimacy arrival watcher timed out for {guest_sim_info.first_name}.", level="WARN")

    time_span = create_time_span(minutes=1)
    alarm_handle = alarms.add_alarm(
        zone_inst,
        time_span,
        _check_arrival,
        repeating=True,
        use_sleep_time=True,
    )
    _INTIMACY_WATCHERS[guest_id] = alarm_handle


def _execute_wicked_sex_now(guest_sim_info: Any, host_sim_info: Any, feedback_fn: Any = None):
    """
    Executes the WickedWhims sex interaction with the active Sim and the partner.
    Supports modes:
    - 'bed_picker': Finds double/single bed and opens WW animation picker dialog.
    - 'nearby_picker': Finds closest sex location object and opens WW animation picker dialog.
    - 'auto_bed': Finds bed and triggers autonomous sex without dialog.
    - 'auto_nearby': Finds closest sex location and triggers autonomous sex without dialog.
    """
    def _out(msg: str, level: str = "INFO"):
        log(f"[ACTION EXECUTOR] {msg}", level=level)
        if feedback_fn:
            try:
                feedback_fn(f"[ACTION DO] {msg}")
            except Exception:
                pass

    if not _is_ww_available():
        err = "WickedWhims is not installed; cannot execute sex action." if _is_en() else "Мод WickedWhims не установлен; невозможно запустить интимное действие."
        _out(err, level="WARN")
        show_chat_notification("WickedWhims", err, is_error=True)
        return

    try:
        try:
            from turbolib2.wrappers.sim.sim import TurboSim
        except Exception:
            from turbolib2.wrappers.sim import TurboSim
        try:
            from turbolib2.wrappers.game_object.game_object import TurboGameObject
        except Exception:
            from turbolib2.wrappers.game_object import TurboGameObject
        try:
            from turbolib2.services.world_service import get_lot_service
        except Exception:
            try:
                from turbolib2.services.lot import get_lot_service
            except Exception:
                get_lot_service = None
        from wickedwhims.sex.integral.sex_handlers.pre_sex.pre_sex_instance import PreSexInteractionInstance
        from wickedwhims.sex.integral.sex_handlers.base_sex_instance import SexInitiationReason
        from wickedwhims.sex.animations.animations_sex_locations import get_sex_location_identifier, SexLocationType
        from wickedwhims.sex.integral.sex_handlers.primitive_sex_init import (
            get_primitive_sex_location_data,
            is_sex_location_always_accept,
        )
        from wickedwhims.sex.generic.sex_reservation_bounds import create_sex_location_reservation_point
        from wickedwhims.sex.integral.sex_handlers.sex_instance_states import SexInstanceStateType
        from wickedwhims.sex.integral.persistence import apply_sim_sex_variables
        from wickedwhims.sex.integral.dialogs.sex_init_player import (
            open_start_sex_animations_categories_picker_dialog,
            open_start_sex_animations_picker_dialog,
        )
        from wickedwhims.sex.autonomy.triggers_handler import (
            trigger_sex_autonomy_interaction,
            get_sex_autonomy_location,
        )
        from ai_thought_reader.config import get_ww_sex_mode
    except Exception as e_imp:
        log_exception("Failed importing WickedWhims modules", e_imp)
        _out(f"Error importing WickedWhims: {e_imp}", level="ERROR")
        return

    active_info = services.active_sim_info() if (services is not None and hasattr(services, "active_sim_info")) else None
    actor_info = host_sim_info if host_sim_info is not None else active_info
    partner_info = guest_sim_info

    if actor_info is None or partner_info is None:
        _out("Cannot start intimacy: SimInfo is missing.", level="ERROR")
        return

    if getattr(actor_info, "sim_id", 0) == getattr(partner_info, "sim_id", 0):
        _out("Cannot start intimacy with self.", level="WARN")
        return

    try:
        turbo_actor = TurboSim(actor_info)
        turbo_partner = TurboSim(partner_info)
    except Exception as e_tsim:
        log_exception("Failed wrapping Sims in TurboSim", e_tsim)
        _out(f"TurboSim creation failed: {e_tsim}", level="ERROR")
        return

    sims_pair = (turbo_actor, turbo_partner)
    sex_mode = get_ww_sex_mode()
    _out(f"Initiating WickedWhims intimacy: {actor_info.first_name} & {partner_info.first_name} (Mode: {sex_mode})")

    # Locate target object
    target_obj = None
    if "bed" in sex_mode:
        target_obj = _find_best_bed_object(actor_info)
        if target_obj is None:
            _out("No bed found on lot; falling back to best available sex location...")
            try:
                target_obj = get_sex_autonomy_location(sims_pair)
            except Exception:
                target_obj = None
    else:
        # Nearby mode
        try:
            target_obj = get_sex_autonomy_location(sims_pair)
        except Exception:
            target_obj = None
        if target_obj is None:
            target_obj = _find_best_bed_object(actor_info)

    if target_obj is None:
        _out("Could not find any suitable object or location for intimacy on the lot.", level="WARN")
        return

    try:
        target_turbo_obj = target_obj if isinstance(target_obj, TurboGameObject) else TurboGameObject(target_obj)
    except Exception as e_wrap:
        log_exception("Failed wrapping target object in TurboGameObject", e_wrap)
        target_turbo_obj = target_obj

    # Branch by mode: Auto vs Picker
    if "auto" in sex_mode:
        try:
            success = trigger_sex_autonomy_interaction(
                sims_pair,
                sex_location=target_turbo_obj,
                ignore_autonomy_restrictions=True,
                is_instant=False,
                force_walk=True,
                force_relationship_check=False,
            )
            _out(f"Triggered autonomous WW sex on {target_turbo_obj} (result={success})")
        except Exception as e_auto:
            log_exception("Failed triggering autonomous sex", e_auto)
            _out(f"Error starting autonomous sex: {e_auto}", level="ERROR")
    else:
        try:
            loc_id = get_sex_location_identifier(target_turbo_obj)
            (game_obj_id, pos, level, angle, route_pos) = get_primitive_sex_location_data(
                target_turbo_obj,
                location_identifier=loc_id,
            )
            res_id = create_sex_location_reservation_point(pos)

            lot_id = get_lot_service().get_current_lot_id() if get_lot_service is not None else 0

            pre_sex = PreSexInteractionInstance(
                None,
                turbo_actor.get_sim_id(),
                loc_id,
                game_obj_id,
                0,
                lot_id,
                pos.x, pos.y, pos.z, level, angle,
                route_pos.x, route_pos.y, route_pos.z, level,
                sex_context_type=None,
                init_reason=SexInitiationReason.DYNAMIC_PLAYER,
                init_location_reservation_id=res_id,
            )

            try:
                if is_sex_location_always_accept(target_turbo_obj):
                    pre_sex.set_as_success()
                    pre_sex.set_state(SexInstanceStateType.ALWAYS_ACCEPT_OBJECT, True)
            except Exception:
                pass

            # Apply sim sex variables to both Sims (which also adds them to pre_sex)
            apply_sim_sex_variables(turbo_actor, turbo_partner, sex_instance=pre_sex)

            # Open WW categories picker dialog
            open_start_sex_animations_categories_picker_dialog(pre_sex)
            _out(f"Opened WickedWhims animation picker dialog for {actor_info.first_name} and {partner_info.first_name}!")
        except Exception as e_picker:
            log_exception("Failed launching sex picker dialog", e_picker)
            _out(f"Error launching sex picker dialog: {e_picker}", level="ERROR")


