# -*- coding: utf-8 -*-
"""
Synapse Mod Localization Synchronizer
Automatically synchronizes all string keys between master Russian strings
and other language files (EN, ES, DE, etc.), and generates embedded mod_strings.py
for packaging into .ts4script.
"""

import os
import sys
import json

SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
MOD_STRINGS_DIR = os.path.join(SCRIPT_DIR, "languages", "mod_strings")
MASTER_EN_PATH = os.path.join(MOD_STRINGS_DIR, "mod_strings_en.json")

TARGET_PY_FILES = [
    os.path.join(SCRIPT_DIR, "src", "ai_thought_reader", "mod_strings.py"),
    os.path.join(SCRIPT_DIR, "src", "ai_social_pc", "mod_strings.py"),
]


def load_json_file(filepath):
    try:
        with open(filepath, "r", encoding="utf-8") as f:
            return json.load(f)
    except Exception as e:
        print(f"[ERROR] Failed to load {filepath}: {e}")
        return None


def save_json_file(filepath, data):
    try:
        with open(filepath, "w", encoding="utf-8") as f:
            json.dump(data, f, ensure_ascii=False, indent=2)
        return True
    except Exception as e:
        print(f"[ERROR] Failed to save {filepath}: {e}")
        return False


def sync_languages():
    if not os.path.isfile(MASTER_EN_PATH):
        print(f"[ERROR] Master EN file not found at {MASTER_EN_PATH}")
        return False

    master_en = load_json_file(MASTER_EN_PATH)
    if not master_en:
        return False

    print("=" * 60)
    print("  SYNAPSE MOD TRANSLATIONS SYNCHRONIZER")
    print("=" * 60)
    print(f"[MASTER] Loaded master English dictionary ({len(master_en)} entries).")

    all_translations = {"en": master_en}

    # Iterate over all other mod_strings_*.json files
    for fname in sorted(os.listdir(MOD_STRINGS_DIR)):
        if fname.startswith("mod_strings_") and fname.endswith(".json") and fname != "mod_strings_en.json":
            lang_code = fname[len("mod_strings_"):-len(".json")]
            fpath = os.path.join(MOD_STRINGS_DIR, fname)
            lang_dict = load_json_file(fpath) or {}

            # Sync keys
            missing_count = 0
            updated_dict = {}

            # Preserve metadata
            meta = lang_dict.get("_metadata", {})
            if not meta:
                meta = {
                    "language": lang_code,
                    "display_name": lang_code.upper(),
                    "description": f"{lang_code.upper()} interface strings for The Sims 4 mod (Synapse)",
                }
            updated_dict["_metadata"] = meta

            for key, master_val in master_en.items():
                if key == "_metadata":
                    continue
                if key in lang_dict and lang_dict[key]:
                    updated_dict[key] = lang_dict[key]
                else:
                    # Missing key: copy from master with [TODO] marker
                    updated_dict[key] = f"[TODO] {master_val}"
                    missing_count += 1

            save_json_file(fpath, updated_dict)
            all_translations[lang_code] = updated_dict

            status = f"SYNCED ({missing_count} missing keys added)" if missing_count > 0 else "UP TO DATE"
            print(f"[LANG] {fname} ({lang_code}): {status}")

    # Generate embedded Python file mod_strings.py
    py_content = (
        "# -*- coding: utf-8 -*-\n"
        "# AUTO-GENERATED BY sync_mod_translations.py - DO NOT EDIT DIRECTLY\n"
        "# Edit languages/mod_strings/mod_strings_*.json instead!\n\n"
        f"MOD_STRINGS = {json.dumps(all_translations, ensure_ascii=False, indent=4)}\n"
    )

    for py_target in TARGET_PY_FILES:
        try:
            os.makedirs(os.path.dirname(py_target), exist_ok=True)
            with open(py_target, "w", encoding="utf-8") as f:
                f.write(py_content)
            print(f"[CODEGEN] Generated embedded strings table:\n  -> {py_target}")
        except Exception as e:
            print(f"[ERROR] Failed to write {py_target}: {e}")

    print("\n[SUCCESS] Translations successfully synchronized across all files!\n")
    return True


if __name__ == "__main__":
    sync_languages()
